{
 "title": "Dashboard_for_estate",
 "time": { "from": "2024-06-04T08:35:13.050Z", "to": "2024-06-04T15:01:56.175Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество запросов к сервису",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "main_app_predictions_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество запросов в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(main_app_predictions_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Процессорное время в минуту",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by (instance) (irate(process_cpu_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение предсказанных цен",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, main_app_predictions_bucket)",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.95, main_app_predictions_bucket)",
     "legendFormat": "quantile(0.95)"
    },
    {
     "expr": "histogram_quantile(0.05, main_app_predictions_bucket)",
     "legendFormat": "quantile(0.05)"
    },
    {
     "expr": "main_app_predictions_sum / main_app_predictions_count",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Текущее потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Время обработки запроса ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "rate(main_app_predictions_count[1m]) / increase(main_app_predictions_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "main_app_predictions_bucket", "legendFormat": "{{le}}" }
   ]
  }
 ]
}