FROM python:3.11-slim
LABEL author=${AUTHOR}
COPY . ./ml_service
WORKDIR ml_service
RUN apt-get update 
RUN pip3 install -r requirements.txt
EXPOSE ${MAIN_APP_PORT}

CMD uvicorn ml_service.main:app --port ${MAIN_APP_PORT} --host 0.0.0.0